spring.application.name=restaurant
spring.datasource.url=jdbc:postgresql://localhost:5432/stack_overflow_restaurant_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true